.TH CALL-SEND 1
.SH NAME
CALL-SEND \- Initiate a phone call using the fone protocol via a foneserver
.SH SYNOPSIS
.B call-send
[\fIphone-number\fR]
.SH DESCRIPTION
.B call-send
is a client which uses the fone protocol to initiate a phone call to a target cell phone number.
It will write a 'hello' to a foneserver control pipe (/tmp/fa2s_ctl) and will wait until the server responds on the receiving control pipe (/tmp/fs2a_ctl) with a private transaction pipe for data exchange.
.B call-send
will then send the transaction over the data pipe to the foneserver and will receive a success of failure reply.
User may send the SIGINT signal to drop the call at any time.
.SH "SEE ALSO"
foneserver(1)
