.TH CALL-SEND 1
.SH NAME
CALL-SEND \- Initiate a phone call using the fone protocol via a foneserver
.SH SYNOPSIS
.B call-send
[\fIphone-number\fR]
.SH DESCRIPTION
.B call-send
is a client which uses the fone protocol to initiate a phone call to a target cell phone number.
It will send a 'hello' command to a foneserver control pipe and will wait until the server responds on the receiving control pipe with a private transaction pipe for data exchange.
It will also subscribe to 'NO CARRIER' so it knows when a target has dropped the call.
It will then send a command transaction ATDnnnnnnnnn; (substituting n's with the target contact phone number) to the server via the data pipes.
User may send the SIGINT signal to drop the call at any time.
By doing this,
.B call-send
will send the server a message 'ATH' as a command transaction.
If the target dropped the call, the subscription thread is cancelled after it sent a finish command transaction.
Then,
.B call-send
will also send a finish command transaction.
.SH "SEE ALSO"
foneserver(1)
